services:
  factorio:
    container_name: factorio-server
    image: miguerubsk/factorio-headless:1.1.110
    restart: unless-stopped

    ports:
      - "34197:34197/udp" # Game Port
      - "27015:27015/tcp" # RCON Port (Optional)

    environment:
      # Basic Configuration
      - SAVE_NAME=factory_world
      - RCON_ENABLED=true
      - RCON_PASSWORD=factorio_secure_pass

      # Dynamic Injector (Optional)
      - FACTORIO_CONF__name=Factorio Headless Server
      - FACTORIO_CONF__description=Simple and clean Factorio server running on Docker.
      - FACTORIO_CONF__visibility__public=false

    volumes:
      - ./data/saves:/factorio/saves
      - ./data/mods:/factorio/mods
      - ./data/config:/factorio/config