services:
  factorio:
    container_name: factorio-server
    image: miguerubsk/factorio-headless:2.0.13
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "pgrep", "factorio"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

    ports:
      - "34197:34197/udp" # Game Port
      - "27015:27015/tcp" # RCON Port (Optional)

    environment:
      # Basic Configuration
      - SAVE_NAME=factory_world
      - RCON_ENABLED=true
      - RCON_PASSWORD=factorio_secure_pass

      # Mod Portal Credentials (Required for Auto-Update)
      - FACTORIO_USER=
      - FACTORIO_TOKEN=
      - MODS_AUTO_UPDATE=false
      - MODS_UPDATE_SCHEDULE=04:00 # Simple HH:MM or Cron expression

      # Game Server Auto-Update
      - GAME_AUTO_UPDATE=false
      - GAME_UPDATE_SCHEDULE=04:00 # Simple HH:MM or Cron expression

      # Space Age DLC (Factorio 2.0+)
      - DLC_SPACE_AGE=true
      - DLC_QUALITY=true
      - DLC_ELEVATED_RAILS=true

      # Dynamic Injector (Optional)
      - FACTORIO_CONF__name=Factorio Headless Server
      - FACTORIO_CONF__description=Simple and clean Factorio server running on Docker.
      - FACTORIO_CONF__visibility__public=false

    volumes:
      - ./data/saves:/factorio/saves
      - ./data/mods:/factorio/mods
      - ./data/config:/factorio/config